//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlNotepad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlNotepad.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string CredentialDialog_DescriptionTextFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.DescriptionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        internal static string CredentialDialog_TitleFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal surrogate character pair 0x{0}, 0x{1} at position {2} in this text node..
        /// </summary>
        internal static string IllegalSurrogatePair {
            get {
                return ResourceManager.GetString("IllegalSurrogatePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href attribute is missing from your XInclude element.
        /// </summary>
        internal static string IncludeHRefRequired {
            get {
                return ResourceManager.GetString("IncludeHRefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character value {0} at position {1} in this text node is illegal in XML documents.  See http://www.w3.org/TR/2006/REC-xml-20060816/#NT-Char..
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading schema &apos;{0}&apos;
        ///{1}.
        /// </summary>
        internal static string SchemaLoadError {
            get {
                return ResourceManager.GetString("SchemaLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema must define same target namespace.
        /// </summary>
        internal static string TNSMismatch {
            get {
                return ResourceManager.GetString("TNSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type converter for type &apos;{0}&apos; not found..
        /// </summary>
        internal static string TypeConvertError {
            get {
                return ResourceManager.GetString("TypeConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected node type &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedNodeType {
            get {
                return ResourceManager.GetString("UnexpectedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos; at line {1} column {2}.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
    }
}
