//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlNotepad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlNotepad.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddSchemaCommand {
            get {
                return ResourceManager.GetString("AddSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple XML editor with XSD intellisense and XSLTpreview.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlNotepad.
        /// </summary>
        internal static string AppProgId {
            get {
                return ResourceManager.GetString("AppProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Load Error.
        /// </summary>
        internal static string AssemblyLoadCaption {
            get {
                return ResourceManager.GetString("AssemblyLoadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly &apos;{0}&apos;
        ///Reason:
        ///{1}.
        /// </summary>
        internal static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string AttributeColor {
            get {
                return ResourceManager.GetString("AttributeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for attributes.
        /// </summary>
        internal static string AttributeColorDescription {
            get {
                return ResourceManager.GetString("AttributeColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoformat long lines instead of prompting.
        /// </summary>
        internal static string AutoFormatLongLinesDescriptions {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoformat Long Lines.
        /// </summary>
        internal static string AutoFormatLongLinesProperty {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on save.
        /// </summary>
        internal static string AutoFormatOnSave {
            get {
                return ResourceManager.GetString("AutoFormatOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to format the XML when it is saved.
        /// </summary>
        internal static string AutoFormatOnSaveDescription {
            get {
                return ResourceManager.GetString("AutoFormatOnSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color for XML notepad workspace.
        /// </summary>
        internal static string BackgroundColorDescription {
            get {
                return ResourceManager.GetString("BackgroundColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Dialog.
        /// </summary>
        internal static string BrowseButtonTooltip {
            get {
                return ResourceManager.GetString("BrowseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDATA.
        /// </summary>
        internal static string CDataColor {
            get {
                return ResourceManager.GetString("CDataColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of CData nodes.
        /// </summary>
        internal static string CDataColorDescription {
            get {
                return ResourceManager.GetString("CDataColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Error.
        /// </summary>
        internal static string ChangeErrorCaption {
            get {
                return ResourceManager.GetString("ChangeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change node to {0}.
        /// </summary>
        internal static string ChangeNodeCommand {
            get {
                return ResourceManager.GetString("ChangeNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string ColorCategory {
            get {
                return ResourceManager.GetString("ColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Color picker....
        /// </summary>
        internal static string ColorPickerLabel {
            get {
                return ResourceManager.GetString("ColorPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentColor {
            get {
                return ResourceManager.GetString("CommentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for comments.
        /// </summary>
        internal static string CommentColorDescription {
            get {
                return ResourceManager.GetString("CommentColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist. Do you need to create the file?.
        /// </summary>
        internal static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        internal static string CreateNodeFileCaption {
            get {
                return ResourceManager.GetString("CreateNodeFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string CredentialDialog_DescriptionTextFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.DescriptionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        internal static string CredentialDialog_TitleFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutCommand {
            get {
                return ResourceManager.GetString("CutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutSchemaCommand {
            get {
                return ResourceManager.GetString("CutSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH:mm:ss.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard the changes you&apos;ve made so far?.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        internal static string DiscardChangesCaption {
            get {
                return ResourceManager.GetString("DiscardChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute with the same name already exists.
        /// </summary>
        internal static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Error.
        /// </summary>
        internal static string DuplicateErrorCaption {
            get {
                return ResourceManager.GetString("DuplicateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dynamic Help tab contains some schema documentation.
        /// </summary>
        internal static string DynamicHelpAvailable {
            get {
                return ResourceManager.GetString("DynamicHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Help.
        /// </summary>
        internal static string DynamicHelpTab {
            get {
                return ResourceManager.GetString("DynamicHelpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Error.
        /// </summary>
        internal static string EditErrorCaption {
            get {
                return ResourceManager.GetString("EditErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        internal static string EditNameCommand {
            get {
                return ResourceManager.GetString("EditNameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Namespace.
        /// </summary>
        internal static string EditNamespaceCommand {
            get {
                return ResourceManager.GetString("EditNamespaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditSchemaCommand {
            get {
                return ResourceManager.GetString("EditSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Value.
        /// </summary>
        internal static string EditValueCommand {
            get {
                return ResourceManager.GetString("EditValueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string ElementColor {
            get {
                return ResourceManager.GetString("ElementColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for elements.
        /// </summary>
        internal static string ElementColorDescription {
            get {
                return ResourceManager.GetString("ElementColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable updates.
        /// </summary>
        internal static string EnableUpdate {
            get {
                return ResourceManager.GetString("EnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to check for updates periodically.
        /// </summary>
        internal static string EnableUpdateDescription {
            get {
                return ResourceManager.GetString("EnableUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorCreatingProcessPrompt {
            get {
                return ResourceManager.GetString("ErrorCreatingProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string ErrorListTab {
            get {
                return ResourceManager.GetString("ErrorListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Changed.
        /// </summary>
        internal static string FileChagedOnDiskCaption {
            get {
                return ResourceManager.GetString("FileChagedOnDiskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are editing has been changed on disk.  Would you like to reload this file?.
        /// </summary>
        internal static string FileChagedOnDiskPrompt {
            get {
                return ResourceManager.GetString("FileChagedOnDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Identical.
        /// </summary>
        internal static string FilesAreIdenticalCaption {
            get {
                return ResourceManager.GetString("FilesAreIdenticalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are identical according to XML Diff.
        /// </summary>
        internal static string FilesAreIdenticalPrompt {
            get {
                return ResourceManager.GetString("FilesAreIdenticalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Error.
        /// </summary>
        internal static string FindErrorCaption {
            get {
                return ResourceManager.GetString("FindErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matching nodes.
        /// </summary>
        internal static string FindNextDonePrompt {
            get {
                return ResourceManager.GetString("FindNextDonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find.
        /// </summary>
        internal static string FindWindowFindTitle {
            get {
                return ResourceManager.GetString("FindWindowFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Replace.
        /// </summary>
        internal static string FindWindowReplaceTitle {
            get {
                return ResourceManager.GetString("FindWindowReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string FontCategory {
            get {
                return ResourceManager.GetString("FontCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font to use in XML notepad workspace.
        /// </summary>
        internal static string FontDesciption {
            get {
                return ResourceManager.GetString("FontDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string FontPropertyName {
            get {
                return ResourceManager.GetString("FontPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Options.
        /// </summary>
        internal static string FormatCategory {
            get {
                return ResourceManager.GetString("FormatCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid DTD validations.
        /// </summary>
        internal static string IgnoreDTDDescription {
            get {
                return ResourceManager.GetString("IgnoreDTDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore DTD.
        /// </summary>
        internal static string IgnoreDTDProperty {
            get {
                return ResourceManager.GetString("IgnoreDTDProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal surrogate character pair 0x{0}, 0x{1} at position {2} in this text node..
        /// </summary>
        internal static string IllegalSurrogatePair {
            get {
                return ResourceManager.GetString("IllegalSurrogatePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href attribute is missing from your XInclude element.
        /// </summary>
        internal static string IncludeHRefRequired {
            get {
                return ResourceManager.GetString("IncludeHRefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent char.
        /// </summary>
        internal static string IndentChar {
            get {
                return ResourceManager.GetString("IndentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent character to use.
        /// </summary>
        internal static string IndentCharDescription {
            get {
                return ResourceManager.GetString("IndentCharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent level.
        /// </summary>
        internal static string IndentLevel {
            get {
                return ResourceManager.GetString("IndentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of indent characters to use for one indent level.
        /// </summary>
        internal static string IndentLevelDescription {
            get {
                return ResourceManager.GetString("IndentLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Error.
        /// </summary>
        internal static string InsertErrorCaption {
            get {
                return ResourceManager.GetString("InsertErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string InsertNodeCommand {
            get {
                return ResourceManager.GetString("InsertNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character value {0} at position {1} in this text node is illegal in XML documents.  See http://www.w3.org/TR/2006/REC-xml-20060816/#NT-Char..
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalError: ISite has not been provided, so model cannot be found.
        /// </summary>
        internal static string ISiteMissing {
            get {
                return ResourceManager.GetString("ISiteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Options.
        /// </summary>
        internal static string LanguageCategory {
            get {
                return ResourceManager.GetString("LanguageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language to select from XSD annotations.
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguagePropertyName {
            get {
                return ResourceManager.GetString("LanguagePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Launching Process.
        /// </summary>
        internal static string LaunchErrorPrompt {
            get {
                return ResourceManager.GetString("LaunchErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded in {0}.
        /// </summary>
        internal static string LoadedTimeStatus {
            get {
                return ResourceManager.GetString("LoadedTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Error.
        /// </summary>
        internal static string LoadErrorCaption {
            get {
                return ResourceManager.GetString("LoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}
        ///{1}
        ///
        ///Would you like to open it using Notepad?.
        /// </summary>
        internal static string LoadErrorPrompt {
            get {
                return ResourceManager.GetString("LoadErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Long Lines.
        /// </summary>
        internal static string LongLineCaption {
            get {
                return ResourceManager.GetString("LongLineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Lines.
        /// </summary>
        internal static string LongLineCategory {
            get {
                return ResourceManager.GetString("LongLineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text in this node contains some very long lines which may make editing this string very slow.  
        ///Would you like to reformat the text into multiple lines?.
        /// </summary>
        internal static string LongLinePrompt {
            get {
                return ResourceManager.GetString("LongLinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Notepad.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the maximum line length before prompting for reformatting?.
        /// </summary>
        internal static string MaximumLineLengthDescription {
            get {
                return ResourceManager.GetString("MaximumLineLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Line Length.
        /// </summary>
        internal static string MaximumLineLengthProperty {
            get {
                return ResourceManager.GetString("MaximumLineLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Error.
        /// </summary>
        internal static string MoveErrorCaption {
            get {
                return ResourceManager.GetString("MoveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line character.
        /// </summary>
        internal static string NewLineChars {
            get {
                return ResourceManager.GetString("NewLineChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character sequence to use for new lines.  &quot;\r&quot; means 0xD and &quot;\n&quot; means 0xA.  So &quot;\r\n&quot; gives you Windows style newlines..
        /// </summary>
        internal static string NewLineCharsDescription {
            get {
                return ResourceManager.GetString("NewLineCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No byte order mark on save.
        /// </summary>
        internal static string NoByteOrderMark {
            get {
                return ResourceManager.GetString("NoByteOrderMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not write any byte order mark at the beginning of the file for UTF-8 (0xef 0xbb 0xbf) or UTF-16 (0xff ffe).
        /// </summary>
        internal static string NoByteOrderMarkDescription {
            get {
                return ResourceManager.GetString("NoByteOrderMarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name of node of type &apos;{0}&apos;.
        /// </summary>
        internal static string NodeNameNotEditable {
            get {
                return ResourceManager.GetString("NodeNameNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Name .
        /// </summary>
        internal static string NodeNameRequiredCaption {
            get {
                return ResourceManager.GetString("NodeNameRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit the value of a node until you provide a node name..
        /// </summary>
        internal static string NodeNameRequiredPrompt {
            get {
                return ResourceManager.GetString("NodeNameRequiredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name of node, node not created yet!.
        /// </summary>
        internal static string NodeNotCreated {
            get {
                return ResourceManager.GetString("NodeNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: node is not a child.
        /// </summary>
        internal static string NotAChild {
            get {
                return ResourceManager.GetString("NotAChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge.
        /// </summary>
        internal static string NudgeCommand {
            get {
                return ResourceManager.GetString("NudgeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Error.
        /// </summary>
        internal static string NudgeErrorCaption {
            get {
                return ResourceManager.GetString("NudgeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|CSV files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PasteCommand {
            get {
                return ResourceManager.GetString("PasteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Error.
        /// </summary>
        internal static string PasteErrorCaption {
            get {
                return ResourceManager.GetString("PasteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI.
        /// </summary>
        internal static string PiColor {
            get {
                return ResourceManager.GetString("PiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of Processing Instruction nodes.
        /// </summary>
        internal static string PiColorDescription {
            get {
                return ResourceManager.GetString("PiColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file is read only, would you like to overwrite &apos;{0}&apos;?.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only File.
        /// </summary>
        internal static string ReadOnlyCaption {
            get {
                return ResourceManager.GetString("ReadOnlyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Error.
        /// </summary>
        internal static string RedoError {
            get {
                return ResourceManager.GetString("RedoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Complete.
        /// </summary>
        internal static string ReplaceCompleteCaption {
            get {
                return ResourceManager.GetString("ReplaceCompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Error.
        /// </summary>
        internal static string ReplaceErrorCaption {
            get {
                return ResourceManager.GetString("ReplaceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all options to the built in defaults, are you sure you want to do that?.
        /// </summary>
        internal static string ResetOptionsPrompt {
            get {
                return ResourceManager.GetString("ResetOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Options.
        /// </summary>
        internal static string ResetOptionsPromptCaption {
            get {
                return ResourceManager.GetString("ResetOptionsPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert attributes at the root level.
        /// </summary>
        internal static string RootLevelAttributes {
            get {
                return ResourceManager.GetString("RootLevelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have anything before the XML declaration.
        /// </summary>
        internal static string RootLevelBeforeXmlDecl {
            get {
                return ResourceManager.GetString("RootLevelBeforeXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have two top level elements.
        /// </summary>
        internal static string RootLevelElements {
            get {
                return ResourceManager.GetString("RootLevelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert text at the root level.
        /// </summary>
        internal static string RootLevelText {
            get {
                return ResourceManager.GetString("RootLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|All files (*.*)|*.*.
        /// </summary>
        internal static string SaveAsFilter {
            get {
                return ResourceManager.GetString("SaveAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChangesCaption {
            get {
                return ResourceManager.GetString("SaveChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        internal static string SaveChangesPrompt {
            get {
                return ResourceManager.GetString("SaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SavedStatus {
            get {
                return ResourceManager.GetString("SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        internal static string SaveErrorCaption {
            get {
                return ResourceManager.GetString("SaveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Errors.
        /// </summary>
        internal static string SaveErrorsCaption {
            get {
                return ResourceManager.GetString("SaveErrorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose XInclude Information.
        /// </summary>
        internal static string SaveExpandedIncludesCaption {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have expanded inline XIncludes, if you save this document you will lose the XInclude elements.  Are you sure you want to do that?.
        /// </summary>
        internal static string SaveExpandedIncludesPrompt {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Error.
        /// </summary>
        internal static string SchemaError {
            get {
                return ResourceManager.GetString("SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading schema &apos;{0}&apos;
        ///{1}.
        /// </summary>
        internal static string SchemaLoadError {
            get {
                return ResourceManager.GetString("SchemaLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Exception of type {0}
        ///{1}.
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text nodes.
        /// </summary>
        internal static string TextColorDescription {
            get {
                return ResourceManager.GetString("TextColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found.
        /// </summary>
        internal static string TextNotFoundPrompt {
            get {
                return ResourceManager.GetString("TextNotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema must define same target namespace.
        /// </summary>
        internal static string TNSMismatch {
            get {
                return ResourceManager.GetString("TNSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to execute XSLT transform.
        /// </summary>
        internal static string TransformButtonTooltip {
            get {
                return ResourceManager.GetString("TransformButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Transforming XML.
        /// </summary>
        internal static string TransformErrorCaption {
            get {
                return ResourceManager.GetString("TransformErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type converter for type &apos;{0}&apos; not found..
        /// </summary>
        internal static string TypeConvertError {
            get {
                return ResourceManager.GetString("TypeConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Error.
        /// </summary>
        internal static string UndoError {
            get {
                return ResourceManager.GetString("UndoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected node type &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedNodeType {
            get {
                return ResourceManager.GetString("UnexpectedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos; at line {1} column {2}.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {1} of {0} is now available.  
        ///Do you want to visit the web page that describes this update?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailableCaption {
            get {
                return ResourceManager.GetString("UpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string UpdateCategory {
            get {
                return ResourceManager.GetString("UpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update location.
        /// </summary>
        internal static string UpdateLocation {
            get {
                return ResourceManager.GetString("UpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of special XML file containing update information.
        /// </summary>
        internal static string UpdateLocationDescription {
            get {
                return ResourceManager.GetString("UpdateLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string UriBrowseLabel {
            get {
                return ResourceManager.GetString("UriBrowseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td title=&apos;{0}&apos;&gt;&lt;b&gt; File in editor : {1}&lt;/b&gt;&lt;/td&gt;
        ///  &lt;td title=&apos;{2}&apos;&gt;&lt;b&gt; File to compare : {2}&lt;/b&gt;&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string XmlDiffBody {
            get {
                return ResourceManager.GetString("XmlDiffBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Diff Error.
        /// </summary>
        internal static string XmlDiffErrorCaption {
            get {
                return ResourceManager.GetString("XmlDiffErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a non-empty name, are you sure you want to leave this name empty?.
        /// </summary>
        internal static string XmlNameEmptyPrompt {
            get {
                return ResourceManager.GetString("XmlNameEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Error.
        /// </summary>
        internal static string XmlNameErrorCaption {
            get {
                return ResourceManager.GetString("XmlNameErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XmlNotepadRegistration {
            get {
                object obj = ResourceManager.GetObject("XmlNotepadRegistration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT files (*.xslt;*.xsl)|*.xslt;*.xsl|All files (*.*)|*.*.
        /// </summary>
        internal static string XSLFileFilter {
            get {
                return ResourceManager.GetString("XSLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter location of XSLT stylesheet you want to use for transforming your XML document.
        /// </summary>
        internal static string XslFileNameTooltip {
            get {
                return ResourceManager.GetString("XslFileNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted Script Code.
        /// </summary>
        internal static string XslScriptCodeCaption {
            get {
                return ResourceManager.GetString("XslScriptCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stylesheet contains untrusted script code.  
        ///Do you want to enable execution of this script code?.
        /// </summary>
        internal static string XslScriptCodePrompt {
            get {
                return ResourceManager.GetString("XslScriptCodePrompt", resourceCulture);
            }
        }
    }
}
