//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlNotepad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlNotepad.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddSchemaCommand {
            get {
                return ResourceManager.GetString("AddSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow analytics.
        /// </summary>
        public static string AllowAnalytics {
            get {
                return ResourceManager.GetString("AllowAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow anonymous analytics to be collected.
        /// </summary>
        public static string AllowAnalyticsDescription {
            get {
                return ResourceManager.GetString("AllowAnalyticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string AnalyticsCategory {
            get {
                return ResourceManager.GetString("AnalyticsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple XML editor with XSD intellisense and XSLTpreview.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlNotepad.
        /// </summary>
        public static string AppProgId {
            get {
                return ResourceManager.GetString("AppProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Load Error.
        /// </summary>
        public static string AssemblyLoadCaption {
            get {
                return ResourceManager.GetString("AssemblyLoadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly &apos;{0}&apos;
        ///Reason:
        ///{1}.
        /// </summary>
        public static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string AttributeColor {
            get {
                return ResourceManager.GetString("AttributeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for attributes.
        /// </summary>
        public static string AttributeColorDescription {
            get {
                return ResourceManager.GetString("AttributeColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoformat long lines instead of prompting.
        /// </summary>
        public static string AutoFormatLongLinesDescriptions {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoformat Long Lines.
        /// </summary>
        public static string AutoFormatLongLinesProperty {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on save.
        /// </summary>
        public static string AutoFormatOnSave {
            get {
                return ResourceManager.GetString("AutoFormatOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to format the XML when it is saved.
        /// </summary>
        public static string AutoFormatOnSaveDescription {
            get {
                return ResourceManager.GetString("AutoFormatOnSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color for XML notepad workspace.
        /// </summary>
        public static string BackgroundColorDescription {
            get {
                return ResourceManager.GetString("BackgroundColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Dialog.
        /// </summary>
        public static string BrowseButtonTooltip {
            get {
                return ResourceManager.GetString("BrowseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDATA.
        /// </summary>
        public static string CDataColor {
            get {
                return ResourceManager.GetString("CDataColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of CData nodes.
        /// </summary>
        public static string CDataColorDescription {
            get {
                return ResourceManager.GetString("CDataColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Error.
        /// </summary>
        public static string ChangeErrorCaption {
            get {
                return ResourceManager.GetString("ChangeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change node to {0}.
        /// </summary>
        public static string ChangeNodeCommand {
            get {
                return ResourceManager.GetString("ChangeNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckUpdatesStatus {
            get {
                return ResourceManager.GetString("CheckUpdatesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string ColorCategory {
            get {
                return ResourceManager.GetString("ColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Color picker....
        /// </summary>
        public static string ColorPickerLabel {
            get {
                return ResourceManager.GetString("ColorPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentColor {
            get {
                return ResourceManager.GetString("CommentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for comments.
        /// </summary>
        public static string CommentColorDescription {
            get {
                return ResourceManager.GetString("CommentColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to Windows Settings for &apos;Default Apps&apos; and select &apos;Choose default apps by file type&apos; add XML Notepad for each file type you want associated with it..
        /// </summary>
        public static string ConfigureDefaultApps {
            get {
                return ResourceManager.GetString("ConfigureDefaultApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container background.
        /// </summary>
        public static string ContainerBackgroundColor {
            get {
                return ResourceManager.GetString("ContainerBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background color for non text nodes.
        /// </summary>
        public static string ContainerBackgroundColorDescription {
            get {
                return ResourceManager.GetString("ContainerBackgroundColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist. Do you need to create the file?.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        public static string CreateNewFileCaption {
            get {
                return ResourceManager.GetString("CreateNewFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutCommand {
            get {
                return ResourceManager.GetString("CutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutSchemaCommand {
            get {
                return ResourceManager.GetString("CutSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH:mm:ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable default XSLT.
        /// </summary>
        public static string DisableDefaultXslt {
            get {
                return ResourceManager.GetString("DisableDefaultXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable default XSLT that just colorizes your XML document in HTML..
        /// </summary>
        public static string DisableDefaultXsltDescription {
            get {
                return ResourceManager.GetString("DisableDefaultXsltDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard the changes you&apos;ve made so far?.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string DiscardChangesCaption {
            get {
                return ResourceManager.GetString("DiscardChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute with the same name already exists.
        /// </summary>
        public static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Error.
        /// </summary>
        public static string DuplicateErrorCaption {
            get {
                return ResourceManager.GetString("DuplicateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dynamic Help tab contains some schema documentation.
        /// </summary>
        public static string DynamicHelpAvailable {
            get {
                return ResourceManager.GetString("DynamicHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Help.
        /// </summary>
        public static string DynamicHelpTab {
            get {
                return ResourceManager.GetString("DynamicHelpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Error.
        /// </summary>
        public static string EditErrorCaption {
            get {
                return ResourceManager.GetString("EditErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string EditingCategory {
            get {
                return ResourceManager.GetString("EditingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        public static string EditNameCommand {
            get {
                return ResourceManager.GetString("EditNameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Namespace.
        /// </summary>
        public static string EditNamespaceCommand {
            get {
                return ResourceManager.GetString("EditNamespaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor background.
        /// </summary>
        public static string EditorBackgroundColor {
            get {
                return ResourceManager.GetString("EditorBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color for text editor control.
        /// </summary>
        public static string EditorBackgroundColorDescription {
            get {
                return ResourceManager.GetString("EditorBackgroundColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditSchemaCommand {
            get {
                return ResourceManager.GetString("EditSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Value.
        /// </summary>
        public static string EditValueCommand {
            get {
                return ResourceManager.GetString("EditValueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string ElementColor {
            get {
                return ResourceManager.GetString("ElementColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color for elements.
        /// </summary>
        public static string ElementColorDescription {
            get {
                return ResourceManager.GetString("ElementColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable updates.
        /// </summary>
        public static string EnableUpdate {
            get {
                return ResourceManager.GetString("EnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to check for updates periodically.
        /// </summary>
        public static string EnableUpdateDescription {
            get {
                return ResourceManager.GetString("EnableUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow execution of script blocks in XSLT stylesheets..
        /// </summary>
        public static string EnableXsltScriptsDescription {
            get {
                return ResourceManager.GetString("EnableXsltScriptsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Scripts.
        /// </summary>
        public static string EnableXsltScriptsPropertyName {
            get {
                return ResourceManager.GetString("EnableXsltScriptsPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching &apos;{0}&apos;.
        /// </summary>
        public static string ErrorCreatingProcessPrompt {
            get {
                return ResourceManager.GetString("ErrorCreatingProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string ErrorListTab {
            get {
                return ResourceManager.GetString("ErrorListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Changed.
        /// </summary>
        public static string FileChagedOnDiskCaption {
            get {
                return ResourceManager.GetString("FileChagedOnDiskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are editing has been changed on disk.  Would you like to reload this file?.
        /// </summary>
        public static string FileChangedOnDiskPrompt {
            get {
                return ResourceManager.GetString("FileChangedOnDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are editing has been renamed on disk.  Would you like to load the new file?.
        /// </summary>
        public static string FileRenamedDiskPrompt {
            get {
                return ResourceManager.GetString("FileRenamedDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to open no longer exists..
        /// </summary>
        public static string FileRenamedOrDeleted {
            get {
                return ResourceManager.GetString("FileRenamedOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Identical.
        /// </summary>
        public static string FilesAreIdenticalCaption {
            get {
                return ResourceManager.GetString("FilesAreIdenticalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are identical according to XML Diff.
        /// </summary>
        public static string FilesAreIdenticalPrompt {
            get {
                return ResourceManager.GetString("FilesAreIdenticalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Error.
        /// </summary>
        public static string FindErrorCaption {
            get {
                return ResourceManager.GetString("FindErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matching nodes.
        /// </summary>
        public static string FindNextDonePrompt {
            get {
                return ResourceManager.GetString("FindNextDonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the &apos;Match whole word&apos; check box but your find string contains spaces.  This doesn&apos;t make sense as the &apos;Match whole word&apos; option can only find individual matching words..
        /// </summary>
        public static string FindWholeWordOnlyFindsWords {
            get {
                return ResourceManager.GetString("FindWholeWordOnlyFindsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find.
        /// </summary>
        public static string FindWindowFindTitle {
            get {
                return ResourceManager.GetString("FindWindowFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Replace.
        /// </summary>
        public static string FindWindowReplaceTitle {
            get {
                return ResourceManager.GetString("FindWindowReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string FontCategory {
            get {
                return ResourceManager.GetString("FontCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font to use in XML notepad workspace.
        /// </summary>
        public static string FontDesciption {
            get {
                return ResourceManager.GetString("FontDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontPropertyName {
            get {
                return ResourceManager.GetString("FontPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Options.
        /// </summary>
        public static string FormatCategory {
            get {
                return ResourceManager.GetString("FormatCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid DTD validations.
        /// </summary>
        public static string IgnoreDTDDescription {
            get {
                return ResourceManager.GetString("IgnoreDTDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore DTD.
        /// </summary>
        public static string IgnoreDTDProperty {
            get {
                return ResourceManager.GetString("IgnoreDTDProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent char.
        /// </summary>
        public static string IndentChar {
            get {
                return ResourceManager.GetString("IndentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent character to use.
        /// </summary>
        public static string IndentCharDescription {
            get {
                return ResourceManager.GetString("IndentCharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent level.
        /// </summary>
        public static string IndentLevel {
            get {
                return ResourceManager.GetString("IndentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of indent characters to use when formatting saved XML documents..
        /// </summary>
        public static string IndentLevelDescription {
            get {
                return ResourceManager.GetString("IndentLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Error.
        /// </summary>
        public static string InsertErrorCaption {
            get {
                return ResourceManager.GetString("InsertErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string InsertNodeCommand {
            get {
                return ResourceManager.GetString("InsertNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name &apos;{0}&apos;.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalError: ISite has not been provided, so model cannot be found.
        /// </summary>
        public static string ISiteMissing {
            get {
                return ResourceManager.GetString("ISiteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Options.
        /// </summary>
        public static string LanguageCategory {
            get {
                return ResourceManager.GetString("LanguageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language to select from XSD annotations.
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguagePropertyName {
            get {
                return ResourceManager.GetString("LanguagePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Launching Process.
        /// </summary>
        public static string LaunchErrorPrompt {
            get {
                return ResourceManager.GetString("LaunchErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded in {0}.
        /// </summary>
        public static string LoadedTimeStatus {
            get {
                return ResourceManager.GetString("LoadedTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Error.
        /// </summary>
        public static string LoadErrorCaption {
            get {
                return ResourceManager.GetString("LoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}
        ///{1}
        ///
        ///Would you like to open it using your text editor?.
        /// </summary>
        public static string LoadErrorPrompt {
            get {
                return ResourceManager.GetString("LoadErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Long Lines.
        /// </summary>
        public static string LongLineCaption {
            get {
                return ResourceManager.GetString("LongLineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Lines.
        /// </summary>
        public static string LongLineCategory {
            get {
                return ResourceManager.GetString("LongLineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text in this node contains some very long lines which may make editing this string very slow.
        ///Would you like to reformat the text into multiple lines?.
        /// </summary>
        public static string LongLinePrompt {
            get {
                return ResourceManager.GetString("LongLinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Notepad.
        /// </summary>
        public static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the maximum line length before prompting for reformatting?.
        /// </summary>
        public static string MaximumLineLengthDescription {
            get {
                return ResourceManager.GetString("MaximumLineLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Line Length.
        /// </summary>
        public static string MaximumLineLengthProperty {
            get {
                return ResourceManager.GetString("MaximumLineLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the maximum length for the textbox.
        /// </summary>
        public static string MaximumValueLengthDescription {
            get {
                return ResourceManager.GetString("MaximumValueLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value Length.
        /// </summary>
        public static string MaximumValueLengthProperty {
            get {
                return ResourceManager.GetString("MaximumValueLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Error.
        /// </summary>
        public static string MoveErrorCaption {
            get {
                return ResourceManager.GetString("MoveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line character.
        /// </summary>
        public static string NewLineChars {
            get {
                return ResourceManager.GetString("NewLineChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character sequence to use for new lines.  &quot;\r&quot; means 0xD and &quot;\n&quot; means 0xA.  So &quot;\r\n&quot; gives you Windows style newlines..
        /// </summary>
        public static string NewLineCharsDescription {
            get {
                return ResourceManager.GetString("NewLineCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No byte order mark on save.
        /// </summary>
        public static string NoByteOrderMark {
            get {
                return ResourceManager.GetString("NoByteOrderMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not write any byte order mark at the beginning of the file for UTF-8 (0xef 0xbb 0xbf) or UTF-16 (0xff ffe).
        /// </summary>
        public static string NoByteOrderMarkDescription {
            get {
                return ResourceManager.GetString("NoByteOrderMarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name of node of type &apos;{0}&apos;.
        /// </summary>
        public static string NodeNameNotEditable {
            get {
                return ResourceManager.GetString("NodeNameNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Name .
        /// </summary>
        public static string NodeNameRequiredCaption {
            get {
                return ResourceManager.GetString("NodeNameRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit the value of a node until you provide a node name..
        /// </summary>
        public static string NodeNameRequiredPrompt {
            get {
                return ResourceManager.GetString("NodeNameRequiredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit name of node, node not created yet!.
        /// </summary>
        public static string NodeNotCreated {
            get {
                return ResourceManager.GetString("NodeNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: node is not a child.
        /// </summary>
        public static string NotAChild {
            get {
                return ResourceManager.GetString("NotAChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge.
        /// </summary>
        public static string NudgeCommand {
            get {
                return ResourceManager.GetString("NudgeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Error.
        /// </summary>
        public static string NudgeErrorCaption {
            get {
                return ResourceManager.GetString("NudgeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|CSV files (*.csv)|*.csv|HTML files (*.htm;*.html)|*.htm;*.html|All files (*.*)|*.*.
        /// </summary>
        public static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteCommand {
            get {
                return ResourceManager.GetString("PasteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Error.
        /// </summary>
        public static string PasteErrorCaption {
            get {
                return ResourceManager.GetString("PasteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI.
        /// </summary>
        public static string PiColor {
            get {
                return ResourceManager.GetString("PiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of Processing Instruction nodes.
        /// </summary>
        public static string PiColorDescription {
            get {
                return ResourceManager.GetString("PiColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file is read only, would you like to overwrite &apos;{0}&apos;?.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only File.
        /// </summary>
        public static string ReadOnlyCaption {
            get {
                return ResourceManager.GetString("ReadOnlyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string RecentFileNotFoundCaption {
            get {
                return ResourceManager.GetString("RecentFileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove it from recent files list?.
        /// </summary>
        public static string RecentFileNotFoundMessage {
            get {
                return ResourceManager.GetString("RecentFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Error.
        /// </summary>
        public static string RedoError {
            get {
                return ResourceManager.GetString("RedoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Complete.
        /// </summary>
        public static string ReplaceCompleteCaption {
            get {
                return ResourceManager.GetString("ReplaceCompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Error.
        /// </summary>
        public static string ReplaceErrorCaption {
            get {
                return ResourceManager.GetString("ReplaceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all options to the built in defaults, are you sure you want to do that?.
        /// </summary>
        public static string ResetOptionsPrompt {
            get {
                return ResourceManager.GetString("ResetOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Options.
        /// </summary>
        public static string ResetOptionsPromptCaption {
            get {
                return ResourceManager.GetString("ResetOptionsPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert attributes at the root level.
        /// </summary>
        public static string RootLevelAttributes {
            get {
                return ResourceManager.GetString("RootLevelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have anything before the XML declaration.
        /// </summary>
        public static string RootLevelBeforeXmlDecl {
            get {
                return ResourceManager.GetString("RootLevelBeforeXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have two top level elements.
        /// </summary>
        public static string RootLevelElements {
            get {
                return ResourceManager.GetString("RootLevelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert text at the root level.
        /// </summary>
        public static string RootLevelText {
            get {
                return ResourceManager.GetString("RootLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples folder not found.
        /// </summary>
        public static string SamplesNotFound {
            get {
                return ResourceManager.GetString("SamplesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|All files (*.*)|*.*.
        /// </summary>
        public static string SaveAsFilter {
            get {
                return ResourceManager.GetString("SaveAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Notepad Save Changes.
        /// </summary>
        public static string SaveChangesCaption {
            get {
                return ResourceManager.GetString("SaveChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string SaveChangesPrompt {
            get {
                return ResourceManager.GetString("SaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedStatus {
            get {
                return ResourceManager.GetString("SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Notepad Save Error.
        /// </summary>
        public static string SaveErrorCaption {
            get {
                return ResourceManager.GetString("SaveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Errors.
        /// </summary>
        public static string SaveErrorsCaption {
            get {
                return ResourceManager.GetString("SaveErrorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose XInclude Information.
        /// </summary>
        public static string SaveExpandedIncludesCaption {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have expanded inline XIncludes, if you save this document you will lose the XInclude elements.  Are you sure you want to do that?.
        /// </summary>
        public static string SaveExpandedIncludesPrompt {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special names that are promoted even without schema information..
        /// </summary>
        public static string SchemaAwareNamesDescription {
            get {
                return ResourceManager.GetString("SchemaAwareNamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special names.
        /// </summary>
        public static string SchemaAwareNamesName {
            get {
                return ResourceManager.GetString("SchemaAwareNamesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema aware text color.
        /// </summary>
        public static string SchemaAwareTextColor {
            get {
                return ResourceManager.GetString("SchemaAwareTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color for schema aware text that is promoted to the parent element..
        /// </summary>
        public static string SchemaAwareTextColorDescription {
            get {
                return ResourceManager.GetString("SchemaAwareTextColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote xsd keys and ids from element content up to the element name row in the TreeView..
        /// </summary>
        public static string SchemaAwareTextDescription {
            get {
                return ResourceManager.GetString("SchemaAwareTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show schema aware text.
        /// </summary>
        public static string SchemaAwareTextName {
            get {
                return ResourceManager.GetString("SchemaAwareTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Options.
        /// </summary>
        public static string SchemaCategory {
            get {
                return ResourceManager.GetString("SchemaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Error.
        /// </summary>
        public static string SchemaError {
            get {
                return ResourceManager.GetString("SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading schema &apos;{0}&apos;
        ///{1}.
        /// </summary>
        public static string SchemaLoadError {
            get {
                return ResourceManager.GetString("SchemaLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsCategory {
            get {
                return ResourceManager.GetString("SettingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings location.
        /// </summary>
        public static string SettingsLocation {
            get {
                return ResourceManager.GetString("SettingsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the XmlNotepad.settings file.
        /// </summary>
        public static string SettingsLocationDescription {
            get {
                return ResourceManager.GetString("SettingsLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open the installer web page..
        /// </summary>
        public static string ShowInstallPage {
            get {
                return ResourceManager.GetString("ShowInstallPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to visit the update history..
        /// </summary>
        public static string ShowUpdateHistory {
            get {
                return ResourceManager.GetString("ShowUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Exception of type {0}
        ///{1}.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text nodes.
        /// </summary>
        public static string TextColorDescription {
            get {
                return ResourceManager.GetString("TextColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text editor to use for View Source option.
        /// </summary>
        public static string TextEditorDescription {
            get {
                return ResourceManager.GetString("TextEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default text editor.
        /// </summary>
        public static string TextEditorProperty {
            get {
                return ResourceManager.GetString("TextEditorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found.
        /// </summary>
        public static string TextNotFoundPrompt {
            get {
                return ResourceManager.GetString("TextNotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        public static string ThemeCategory {
            get {
                return ResourceManager.GetString("ThemeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default color theme and theme to edit.
        /// </summary>
        public static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to execute XSLT transform.
        /// </summary>
        public static string TransformButtonTooltip {
            get {
                return ResourceManager.GetString("TransformButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed in {0} ms and {2} loaded in {1} ms.
        /// </summary>
        public static string TransformedTimeStatus {
            get {
                return ResourceManager.GetString("TransformedTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Transforming XML.
        /// </summary>
        public static string TransformErrorCaption {
            get {
                return ResourceManager.GetString("TransformErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView indent pixels.
        /// </summary>
        public static string TreeIndent {
            get {
                return ResourceManager.GetString("TreeIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pixels to indent XML in the TreeView..
        /// </summary>
        public static string TreeIndentDescription {
            get {
                return ResourceManager.GetString("TreeIndentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Error.
        /// </summary>
        public static string UndoError {
            get {
                return ResourceManager.GetString("UndoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected node type &apos;{0}&apos;.
        /// </summary>
        public static string UnexpectedNodeType {
            get {
                return ResourceManager.GetString("UnexpectedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailableCaption {
            get {
                return ResourceManager.GetString("UpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {1} of {0} is now available. .
        /// </summary>
        public static string UpdateAvailableTooltip {
            get {
                return ResourceManager.GetString("UpdateAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdateCategory {
            get {
                return ResourceManager.GetString("UpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update location.
        /// </summary>
        public static string UpdateLocation {
            get {
                return ResourceManager.GetString("UpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of special XML file containing update information.
        /// </summary>
        public static string UpdateLocationDescription {
            get {
                return ResourceManager.GetString("UpdateLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version: {0}.
        /// </summary>
        public static string UpToDateTooltip {
            get {
                return ResourceManager.GetString("UpToDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        public static string UriBrowseLabel {
            get {
                return ResourceManager.GetString("UriBrowseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which version of Web Browser to use to render XSLT output..
        /// </summary>
        public static string WebBrowserDescription {
            get {
                return ResourceManager.GetString("WebBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser Version.
        /// </summary>
        public static string WebBrowserPropertyName {
            get {
                return ResourceManager.GetString("WebBrowserPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing WebView2 component. Do you want to try and re-install the WebView2 component?
        ///
        ///Error: {0}.
        /// </summary>
        public static string WebView2Error {
            get {
                return ResourceManager.GetString("WebView2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Initialization Error.
        /// </summary>
        public static string WebView2ErrorTitle {
            get {
                return ResourceManager.GetString("WebView2ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XSLT output is using an older web browser, if you want faster and more up to date HTML rendering support do you want to install WebView2 ?.
        /// </summary>
        public static string WebView2InstallPrompt {
            get {
                return ResourceManager.GetString("WebView2InstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will download the WebView2 setup program named &quot;MicrosoftEdgeWebview2Setup&quot;, and you will find it in your downloads folder.  When the download is finished please run it then restart XML Notepad..
        /// </summary>
        public static string WebView2InstallReady {
            get {
                return ResourceManager.GetString("WebView2InstallReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView Upgrade.
        /// </summary>
        public static string WebView2InstallTitle {
            get {
                return ResourceManager.GetString("WebView2InstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td title=&apos;{0}&apos;&gt;&lt;b&gt; File in editor : {1}&lt;/b&gt;&lt;/td&gt;
        ///  &lt;td title=&apos;{2}&apos;&gt;&lt;b&gt; File to compare : {3}&lt;/b&gt;&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        public static string XmlDiffBody {
            get {
                return ResourceManager.GetString("XmlDiffBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file loaded to diff against..
        /// </summary>
        public static string XmlDiffEmptyPrompt {
            get {
                return ResourceManager.GetString("XmlDiffEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Diff Error.
        /// </summary>
        public static string XmlDiffErrorCaption {
            get {
                return ResourceManager.GetString("XmlDiffErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string XmlDiffHideIdenticalDescription {
            get {
                return ResourceManager.GetString("XmlDiffHideIdenticalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide identical.
        /// </summary>
        public static string XmlDiffHideIdenticalProperty {
            get {
                return ResourceManager.GetString("XmlDiffHideIdenticalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in the order of child elements.
        /// </summary>
        public static string XmlDiffIgnoreChildOrderDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreChildOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore child order.
        /// </summary>
        public static string XmlDiffIgnoreChildOrderProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreChildOrderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in comments.
        /// </summary>
        public static string XmlDiffIgnoreCommentsDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreCommentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore comments.
        /// </summary>
        public static string XmlDiffIgnoreCommentsProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreCommentsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in DTD elements.
        /// </summary>
        public static string XmlDiffIgnoreDtdDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreDtdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore DTD.
        /// </summary>
        public static string XmlDiffIgnoreDtdProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreDtdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in namespaces.
        /// </summary>
        public static string XmlDiffIgnoreNamespacesDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreNamespacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore namespaces.
        /// </summary>
        public static string XmlDiffIgnoreNamespacesProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreNamespacesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in processing instructions.
        /// </summary>
        public static string XmlDiffIgnorePIDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnorePIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore processing instructions.
        /// </summary>
        public static string XmlDiffIgnorePIProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnorePIProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in namespace prefixes.
        /// </summary>
        public static string XmlDiffIgnorePrefixesDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnorePrefixesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore prefixes.
        /// </summary>
        public static string XmlDiffIgnorePrefixesProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnorePrefixesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in insignificant whitespace between elements.
        /// </summary>
        public static string XmlDiffIgnoreWhitespaceDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreWhitespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore whitespace.
        /// </summary>
        public static string XmlDiffIgnoreWhitespaceProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreWhitespaceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore differences in XML declarations.
        /// </summary>
        public static string XmlDiffIgnoreXmlDeclDescription {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreXmlDeclDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore XML declarations.
        /// </summary>
        public static string XmlDiffIgnoreXmlDeclProperty {
            get {
                return ResourceManager.GetString("XmlDiffIgnoreXmlDeclProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected the same file, please select a different file..
        /// </summary>
        public static string XmlDiffSameFilePrompt {
            get {
                return ResourceManager.GetString("XmlDiffSameFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a non-empty name, are you sure you want to leave this name empty?.
        /// </summary>
        public static string XmlNameEmptyPrompt {
            get {
                return ResourceManager.GetString("XmlNameEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Error.
        /// </summary>
        public static string XmlNameErrorCaption {
            get {
                return ResourceManager.GetString("XmlNameErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT files (*.xslt;*.xsl)|*.xslt;*.xsl|All files (*.*)|*.*.
        /// </summary>
        public static string XSLFileFilter {
            get {
                return ResourceManager.GetString("XSLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter location of XSLT stylesheet you want to use for transforming your XML document.
        /// </summary>
        public static string XslFileNameTooltip {
            get {
                return ResourceManager.GetString("XslFileNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the filename for storing the the XSLT output.
        /// </summary>
        public static string XslOutputFileNameTooltip {
            get {
                return ResourceManager.GetString("XslOutputFileNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted Script Code.
        /// </summary>
        public static string XslScriptCodeCaption {
            get {
                return ResourceManager.GetString("XslScriptCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stylesheet contains untrusted script code.
        ///Do you want to enable execution of this script code?.
        /// </summary>
        public static string XslScriptCodePrompt {
            get {
                return ResourceManager.GetString("XslScriptCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT.
        /// </summary>
        public static string XsltCategory {
            get {
                return ResourceManager.GetString("XsltCategory", resourceCulture);
            }
        }
    }
}
