  # This is a basic workflow to help you get started with Actions

name: Mkdocs publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install pip
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Install MkDocs
        run: |
          pip install mkdocs
          pip install mkdocs-macros-plugin

      - name: MkDocs build
        run: mkdocs build

      - name: MkDocs deploy
        run: mkdocs gh-deploy --force
